function on_game_start()
    local ini_bas_ammo = ini_file("items\\ammo\\bas_ammo.ltx")
    ini_bas_ammo:section_for_each(function(ammo)
        local count = ini_bas_ammo:line_count(ammo) or 0
        for i=0,count-1 do
            local result, id, value = ini_bas_ammo:r_line(ammo , i , "", "")
            printf("assigning ammo %s recipe %s", id, value)
            workshop_autoinject.add_new_recipe(6, id, value)
        end
    end)
end