
function on_game_start()
	workshop_autoinject.add_new_recipe(1, "detonator_homemade","1, recipe_basic_0, radio,1,radio2,1,prt_i_copper,1,batteries_dead,1")
	workshop_autoinject.add_new_recipe(1, "detonator_disarm","2, recipe_advanced_0, detector_radio,1,prt_i_copper,1,batteries_dead,1,mirror,1")

	workshop_autoinject.add_new_recipe(6, "remote_ied","1, recipe_ammo_0, ied_new,1,prt_i_copper,1,radio,1")
	workshop_autoinject.add_new_recipe(6, "remote_ied","1, recipe_ammo_0, ied_new,1,prt_i_copper,1,radio2,1")
	workshop_autoinject.add_new_recipe(6, "remote_ied_rpg","1, recipe_ammo_0, ied_rpg_new,1,prt_i_copper,1,radio,1")
	workshop_autoinject.add_new_recipe(6, "remote_ied_rpg","1, recipe_ammo_0, ied_rpg_new,1,prt_i_copper,1,radio2,1")

	workshop_autoinject.add_new_recipe(6, "ied_new","2, recipe_advanced_2, explo_metalcan_powder,1,explo_balon_gas,1,duct_tape,1,prt_i_fasteners,3")
	workshop_autoinject.add_new_recipe(6, "ied_new","2, recipe_advanced_2, explo_metalcan_powder,1,kerosene,1,duct_tape,1,prt_i_fasteners,3")
	workshop_autoinject.add_new_recipe(6, "ied_rpg_new","2, recipe_advanced_1,ammo_og-7b,1,batteries_dead,1,prt_i_copper,1,prt_i_fasteners,1")
	workshop_autoinject.add_new_recipe(6, "ied_rpg_new","2, recipe_advanced_1,ammo_og-7b_bad,1,batteries_dead,1,prt_i_copper,2,prt_i_fasteners,2")

end